; MemberVariableLayout.ini for Palworld (UE5.1)
; Based on the official UE5.1 template from RE-UE4SS
; with Palworld-specific UEnum::Names fix (0x40 -> 0x48)
; Place this file next to libUE4SS.so

[UObjectBase]
ObjectFlags = 0x8
InternalIndex = 0xC
ClassPrivate = 0x10
NamePrivate = 0x18
OuterPrivate = 0x20
UEP_TotalSize = 0x28

[UScriptStruct::ICppStructOps]
Size = 0x8
Alignment = 0xC
UEP_TotalSize = 0x10

[FOutputDevice]
bSuppressEventTag = 0x8
bAutoEmitLineTerminator = 0x9
UEP_TotalSize = 0x10

[UStruct]
SuperStruct = 0x40
Children = 0x48
ChildProperties = 0x50
PropertiesSize = 0x58
MinAlignment = 0x5C
Script = 0x60
PropertyLink = 0x70
RefLink = 0x78
DestructorLink = 0x80
PostConstructLink = 0x88
ScriptAndPropertyObjectReferences = 0x90
UnresolvedScriptProperties = 0xA0
UEP_TotalSize = 0xB0

[UGameViewportClient]
ViewportConsole = 0x40
DebugProperties = 0x48
SplitscreenInfo = 0x58
MaxSplitscreenPlayers = 0x68
bShowTitleSafeZone = 0x6C:0:1:4
bIsPlayInEditorViewport = 0x6C:1:1:4
bDisableWorldRendering = 0x6C:2:1:4
ActiveSplitscreenType = 0x70
World = 0x78
bSuppressTransitionMessage = 0x88
ViewModeIndex = 0xB0
EngineShowFlags = 0xB8
Viewport = 0xE8
ViewportFrame = 0xF0
AudioDeviceHandle = 0xF8
bHasAudioFocus = 0xFC
Window = 0x100
ViewportOverlayWidget = 0x110
GameLayerManagerPtr = 0x120
CurrentBufferVisualizationMode = 0x130
CurrentNaniteVisualizationMode = 0x138
CurrentLumenVisualizationMode = 0x140
CurrentVirtualShadowMapVisualizationMode = 0x148
HighResScreenshotDialog = 0x150
HardwareCursorCache = 0x160
HardwareCursors = 0x1B0
CursorWidgets = 0x200
bUseSoftwareCursorWidgets = 0x250
StatUnitData = 0x388
StatHitchesData = 0x390
bDisableSplitScreenOverride = 0x398
bIgnoreInput = 0x399
MouseCaptureMode = 0x39A
bHideCursorDuringCapture = 0x39B
MouseLockMode = 0x39C
bIsMouseOverClient = 0x39D
UEP_TotalSize = 0x3A0

[FUObjectItem]
Object = 0x0
Flags = 0x8
ClusterRootIndex = 0xC
SerialNumber = 0x10
UEP_TotalSize = 0x18

[FUObjectArray]
ObjFirstGCIndex = 0x0
ObjLastNonGCIndex = 0x4
MaxObjectsNotConsideredByGC = 0x8
OpenForDisregardForGC = 0xC
ObjObjects = 0x10
ObjAvailableList = 0x58
UObjectCreateListeners = 0x68
UObjectDeleteListeners = 0x78
PrimarySerialNumber = 0xB0
UEP_TotalSize = 0xB8

[TUObjectArray]
Objects = 0x0
PreAllocatedObjects = 0x8
MaxElements = 0x10
NumElements = 0x14
MaxChunks = 0x18
NumChunks = 0x1C
UEP_TotalSize = 0x20

[FArchiveState]
ArIsLoading = 0x28:0:1:1
ArIsLoadingFromCookedPackage = 0x28:1:1:1
ArIsSaving = 0x28:2:1:1
ArIsTransacting = 0x28:3:1:1
ArIsTextFormat = 0x28:4:1:1
ArWantBinaryPropertySerialization = 0x28:5:1:1
ArUseUnversionedPropertySerialization = 0x28:6:1:1
ArForceUnicode = 0x28:7:1:1
ArIsPersistent = 0x29:0:1:1
ArIsError = 0x29:1:1:1
ArIsCriticalError = 0x29:2:1:1
ArShouldSkipCompilingAssets = 0x29:3:1:1
ArContainsCode = 0x29:4:1:1
ArContainsMap = 0x29:5:1:1
ArRequiresLocalizationGather = 0x29:6:1:1
ArForceByteSwapping = 0x29:7:1:1
ArIgnoreArchetypeRef = 0x2A:0:1:1
ArNoDelta = 0x2A:1:1:1
ArNoIntraPropertyDelta = 0x2A:2:1:1
ArIgnoreOuterRef = 0x2A:3:1:1
ArIgnoreClassGeneratedByRef = 0x2A:4:1:1
ArIgnoreClassRef = 0x2A:5:1:1
ArAllowLazyLoading = 0x2A:6:1:1
ArIsObjectReferenceCollector = 0x2A:7:1:1
ArIsModifyingWeakAndStrongReferences = 0x2B:0:1:1
ArIsCountingMemory = 0x2B:1:1:1
ArShouldSkipBulkData = 0x2B:2:1:1
ArIsFilterEditorOnly = 0x2B:3:1:1
ArIsSaveGame = 0x2B:4:1:1
ArIsNetArchive = 0x2B:5:1:1
ArUseCustomPropertyList = 0x2B:6:1:1
ArSerializingDefaults = 0x2C
ArPortFlags = 0x30
ArMaxSerializeSize = 0x38
ArUEVer = 0x40
ArLicenseeUEVer = 0x48
ArEngineVer = 0x4C
ArEngineNetVer = 0x58
ArGameNetVer = 0x5C
CustomVersionContainer = 0x60
ArCustomPropertyList = 0x68
SerializedProperty = 0x78
bCustomVersionsAreReset = 0x88
NextProxy = 0x90
UEP_TotalSize = 0x98

[AGameModeBase]
OptionsString = 0x290
GameSessionClass = 0x2A0
PlayerStateClass = 0x2B8
HUDClass = 0x2C0
SpectatorClass = 0x2D0
ServerStatReplicatorClass = 0x2E0
GameSession = 0x2E8
ServerStatReplicator = 0x2F8
DefaultPlayerName = 0x300
bUseSeamlessTravel = 0x318:0:1:4
bStartPlayersAsSpectators = 0x318:1:1:4
bPauseable = 0x318:2:1:4
UEP_TotalSize = 0x330

[AGameMode]
MatchState = 0x330
bDelayedStart = 0x338:0:1:4
NumSpectators = 0x33C
NumPlayers = 0x340
NumBots = 0x344
MinRespawnDelay = 0x348
NumTravellingPlayers = 0x34C
EngineMessageClass = 0x350
InactivePlayerArray = 0x358
InactivePlayerStateLifeSpan = 0x368
MaxInactivePlayers = 0x36C
bHandleDedicatedServerReplays = 0x370
UEP_TotalSize = 0x378

[AActor]
PrimaryActorTick = 0x28
bNetTemporary = 0x58:0:1:1
bNetStartup = 0x58:1:1:1
bOnlyRelevantToOwner = 0x58:2:1:1
bAlwaysRelevant = 0x58:3:1:1
bReplicateMovement = 0x58:4:1:1
bCallPreReplication = 0x58:5:1:1
bCallPreReplicationForReplay = 0x58:6:1:1
bHidden = 0x58:7:1:1
bTearOff = 0x59:0:1:1
bForceNetAddressable = 0x59:1:1:1
bExchangedRoles = 0x59:2:1:1
bNetLoadOnClient = 0x59:3:1:1
bNetUseOwnerRelevancy = 0x59:4:1:1
bRelevantForNetworkReplays = 0x59:5:1:1
bRelevantForLevelBounds = 0x59:6:1:1
bReplayRewindable = 0x59:7:1:1
bAllowTickBeforeBeginPlay = 0x5A:0:1:1
bAutoDestroyWhenFinished = 0x5A:1:1:1
bCanBeDamaged = 0x5A:2:1:1
bBlockInput = 0x5A:3:1:1
bCollideWhenPlacing = 0x5A:4:1:1
bFindCameraComponentWhenViewTarget = 0x5A:5:1:1
bGenerateOverlapEventsDuringLevelStreaming = 0x5A:6:1:1
bIgnoresOriginShifting = 0x5A:7:1:1
bEnableAutoLODGeneration = 0x5B:0:1:1
bIsEditorOnlyActor = 0x5B:1:1:1
bActorSeamlessTraveled = 0x5B:2:1:1
bReplicates = 0x5B:3:1:1
bCanBeInCluster = 0x5B:4:1:1
bAllowReceiveTickEventOnDedicatedServer = 0x5B:5:1:1
bNetCheckedInitialPhysicsState = 0x5B:6:1:1
bReplicateUsingRegisteredSubObjectList = 0x5B:7:1:1
bHasFinishedSpawning = 0x5C:0:1:1
bActorInitialized = 0x5C:1:1:1
bActorBeginningPlayFromLevelStreaming = 0x5C:2:1:1
bTickFunctionsRegistered = 0x5C:3:1:1
bHasDeferredComponentRegistration = 0x5C:4:1:1
bRunningUserConstructionScript = 0x5C:5:1:1
bHasRegisteredAllComponents = 0x5C:6:1:1
bActorEnableCollision = 0x5C:7:1:1
bActorIsBeingDestroyed = 0x5D:0:1:1
bActorWantsDestroyDuringBeginPlay = 0x5D:1:1:1
ActorHasBegunPlay = 0x5D:2:2:1
bActorIsBeingConstructed = 0x5D:4:1:1
bAsyncPhysicsTickEnabled = 0x5D:5:1:1
UpdateOverlapsMethodDuringLevelStreaming = 0x5E
DefaultUpdateOverlapsMethodDuringLevelStreaming = 0x5F
InitialLifeSpan = 0x60
CustomTimeDilation = 0x64
RemoteRole = 0x68
RayTracingGroupId = 0x6C
AttachmentReplication = 0x70
ReplicatedMovement = 0xD0
Owner = 0x140
NetDriverName = 0x148
Role = 0x150
NetDormancy = 0x151
SpawnCollisionHandlingMethod = 0x152
AutoReceiveInput = 0x153
InputPriority = 0x154
CreationTime = 0x158
InputComponent = 0x160
NetCullDistanceSquared = 0x168
NetTag = 0x16C
NetUpdateFrequency = 0x170
MinNetUpdateFrequency = 0x174
NetPriority = 0x178
LastRenderTime = 0x17C
Children = 0x188
RootComponent = 0x198
TimerHandle_LifeSpanExpired = 0x1A0
Layers = 0x1A8
ParentComponent = 0x1B8
Tags = 0x1C0
OnTakeAnyDamage = 0x1D0
OnTakePointDamage = 0x1D1
OnTakeRadialDamage = 0x1D2
OnActorBeginOverlap = 0x1D3
OnActorEndOverlap = 0x1D4
OnBeginCursorOver = 0x1D5
OnEndCursorOver = 0x1D6
OnClicked = 0x1D7
OnReleased = 0x1D8
OnInputTouchBegin = 0x1D9
OnInputTouchEnd = 0x1DA
OnInputTouchEnter = 0x1DB
OnInputTouchLeave = 0x1DC
OnActorHit = 0x1DD
OnDestroyed = 0x1DE
OnEndPlay = 0x1DF
ReplicatedSubObjects = 0x1E0
ReplicatedComponentsInfo = 0x1F0
DetachFence = 0x280
UEP_TotalSize = 0x290

[UPlayer]
CurrentNetSpeed = 0x38
ConfiguredInternetSpeed = 0x3C
ConfiguredLanSpeed = 0x40
UEP_TotalSize = 0x48

[ULocalPlayer]
CachedUniqueNetId = 0x48
ViewportClient = 0x78
AspectRatioAxisConstraint = 0xB8
bSentSplitJoin = 0xC8:0:1:4
ControllerId = 0xE0
PlatformUserId = 0x100
SlateOperations = 0x1E0
UEP_TotalSize = 0x298

[FFieldClass]
Name = 0x0
Id = 0x8
CastFlags = 0x10
ClassFlags = 0x18
SuperClass = 0x20
DefaultObject = 0x28
ConstructFn = 0x30
UnqiueNameIndexCounter = 0x38
UEP_TotalSize = 0x40

[FField]
ClassPrivate = 0x8
Owner = 0x10
Next = 0x20
NamePrivate = 0x28
FlagsPrivate = 0x30
UEP_TotalSize = 0x38

[UField]
Next = 0x28
UEP_TotalSize = 0x30

[FProperty]
ArrayDim = 0x38
ElementSize = 0x3C
PropertyFlags = 0x40
RepIndex = 0x48
Offset_Internal = 0x4C
RepNotifyFunc = 0x50
PropertyLinkNext = 0x58
NextRef = 0x60
DestructorLinkNext = 0x68
PostConstructLinkNext = 0x70
UEP_TotalSize = 0x78

[FMulticastDelegateProperty]
SignatureFunction = 0x78
UEP_TotalSize = 0x80

[FObjectPropertyBase]
PropertyClass = 0x78
UEP_TotalSize = 0x80

[FWorldContext]
ContextHandle = 0xA0
TravelURL = 0xA8
TravelType = 0xB8
LastURL = 0xC0
LastRemoteURL = 0x128
LevelsToLoadForPendingMapChange = 0x1A8
PendingMapChangeFailureDescription = 0x1C8
bShouldCommitPendingMapChange = 0x1D8:0:1:4
GameViewport = 0x200
PIEInstance = 0x220
PIEPrefix = 0x228
RunAsDedicated = 0x23C
bWaitingOnOnlineSubsystem = 0x23D
bIsPrimaryPIEInstance = 0x23E
AudioDeviceID = 0x240
CustomDescription = 0x248
PIEFixedTickSeconds = 0x258
PIEAccumulatedTickSeconds = 0x25C
GarbageObjectsToVerify = 0x260
ExternalReferences = 0x2B0
ThisCurrentWorld = 0x2C0
UEP_TotalSize = 0x2C8

[UScriptStruct]
StructFlags = 0xB0
bPrepareCppStructOpsCompleted = 0xB4
CppStructOps = 0xB8
UEP_TotalSize = 0xC0

[UWorld]
ExtraReferencedObjects = 0x68
PerModuleDataObjects = 0x78
StreamingLevelsPrefix = 0xC8
bSupportsMakingVisibleTransactionRequests = 0xD8
bSupportsMakingInvisibleTransactionRequests = 0xDA
bAllowDeferredPhysicsStateCreation = 0x108
LastRenderTime = 0x130
bWorldWasLoadedThisTick = 0x13B:0:1:1
bTriggerPostLoadMap = 0x13B:1:1:1
bInTick = 0x13B:2:1:1
bIsBuilt = 0x13B:3:1:1
bTickNewlySpawned = 0x13B:4:1:1
bPostTickComponentUpdate = 0x13B:5:1:1
bIsWorldInitialized = 0x13B:6:1:1
bIsLevelStreamingFrozen = 0x13B:7:1:1
bDoDelayedUpdateCullDistanceVolumes = 0x13C:0:1:1
bIsRunningConstructionScript = 0x13C:1:1:1
bShouldSimulatePhysics = 0x13C:2:1:1
bDropDetail = 0x13C:3:1:1
bAggressiveLOD = 0x13C:4:1:1
bIsDefaultLevel = 0x13C:5:1:1
bRequestedBlockOnAsyncLoading = 0x13C:6:1:1
bActorsInitialized = 0x13C:7:1:1
bBegunPlay = 0x13D:0:1:1
bMatchStarted = 0x13D:1:1:1
bPlayersOnly = 0x13D:2:1:1
bPlayersOnlyPending = 0x13D:3:1:1
bStartup = 0x13D:4:1:1
bIsTearingDown = 0x13D:5:1:1
bKismetScriptError = 0x13D:6:1:1
bDebugPauseExecution = 0x13D:7:1:1
bIsCameraMoveableWhenPaused = 0x13E:0:1:1
bAllowAudioPlayback = 0x13E:1:1:1
bAreConstraintsDirty = 0x13E:2:1:1
bRequiresHitProxies = 0x13E:3:1:1
bShouldTick = 0x13E:4:1:1
bStreamingDataDirty = 0x13E:5:1:1
bShouldForceUnloadStreamingLevels = 0x13E:6:1:1
bShouldForceVisibleStreamingLevels = 0x13E:7:1:1
bMaterialParameterCollectionInstanceNeedsDeferredUpdate = 0x13F:0:1:1
bHasEverBeenInitialized = 0x13F:1:1:1
IsInBlockTillLevelStreamingCompleted = 0x140
BlockTillLevelStreamingCompletedEpoch = 0x144
AuthorityGameMode = 0x150
ActiveLevelCollectionIndex = 0x190
LWILastAssignedUID = 0x258
BuildStreamingDataTimer = 0x448
URL = 0x540
PlayerNum = 0x618
StreamingVolumeUpdateDelay = 0x61C
LastTimeUnbuiltLightingWasEncountered = 0x658
TimeSeconds = 0x660
UnpausedTimeSeconds = 0x668
RealTimeSeconds = 0x670
AudioTimeSeconds = 0x678
DeltaRealTimeSeconds = 0x680
DeltaTimeSeconds = 0x684
PauseDelay = 0x688
NextSwitchCountdown = 0x6C0
NumStreamingLevelsBeingLoaded = 0x6DA
NextURL = 0x6E0
PreparingLevelNames = 0x6F0
CommittedPersistentLevelName = 0x700
bMarkedObjectsPendingKill = 0x708:0:1:4
CleanupWorldTag = 0x70C
UEP_TotalSize = 0x898

[UFunction]
FunctionFlags = 0xB0
NumParms = 0xB4
ParmsSize = 0xB6
ReturnValueOffset = 0xB8
RPCId = 0xBA
RPCResponseId = 0xBC
FirstPropertyToInit = 0xC0
EventGraphFunction = 0xC8
EventGraphCallOffset = 0xD0
Func = 0xD8
UEP_TotalSize = 0xE0

[UClass]
ClassConstructor = 0xB0
ClassVTableHelperCtorCaller = 0xB8
ClassUnique = 0xC8
FirstOwnedClassRep = 0xCC
bCooked = 0xD0
bLayoutChanging = 0xD1
ClassFlags = 0xD4
ClassCastFlags = 0xD8
ClassWithin = 0xE0
ClassConfigName = 0xE8
NetFields = 0x100
ClassDefaultObject = 0x110
SparseClassData = 0x118
SparseClassDataStruct = 0x120
FuncMap = 0x128
SuperFuncMap = 0x178
Interfaces = 0x1D0
ReferenceTokenStream = 0x1E0
NativeFunctionLookupTable = 0x220
UEP_TotalSize = 0x230

; Palworld-specific: UEnum::Names is 0x48 (not 0x40 as in stock UE5.1)
; Also EnumFlags_Internal instead of EnumFlags
[UEnum]
CppType = 0x30
Names = 0x48
CppForm = 0x50
EnumFlags_Internal = 0x5C
EnumDisplayNameFn = 0x60
EnumPackage = 0x68
UEP_TotalSize = 0x68

[FStructProperty]
Struct = 0x78
UEP_TotalSize = 0x80

[FArrayProperty]
Inner = 0x78
ArrayFlags = 0x80
UEP_TotalSize = 0x88

[FMapProperty]
KeyProp = 0x78
ValueProp = 0x80
MapLayout = 0x88
MapFlags = 0xA0
UEP_TotalSize = 0xA8

[FBoolProperty]
FieldSize = 0x78
ByteOffset = 0x79
ByteMask = 0x7A
FieldMask = 0x7B
UEP_TotalSize = 0x80

[FByteProperty]
Enum = 0x78
UEP_TotalSize = 0x80

[FEnumProperty]
UnderlyingProp = 0x78
Enum = 0x80
UEP_TotalSize = 0x88

[FClassProperty]
MetaClass = 0x80
UEP_TotalSize = 0x88

[FSoftClassProperty]
MetaClass = 0x80
UEP_TotalSize = 0x88

[FDelegateProperty]
SignatureFunction = 0x78
UEP_TotalSize = 0x80

[FInterfaceProperty]
InterfaceClass = 0x78
UEP_TotalSize = 0x80

[FFieldPathProperty]
PropertyClass = 0x78
UEP_TotalSize = 0x80

[FSetProperty]
ElementProp = 0x78
SetLayout = 0x80
UEP_TotalSize = 0x98

[UDataTable]
RowStruct = 0x28
RowMap = 0x30
bStripFromClientBuilds = 0x80:0:1:1
bIgnoreExtraFields = 0x80:1:1:1
bIgnoreMissingFields = 0x80:2:1:1
ImportKeyField = 0x88
UEP_TotalSize = 0xB0

[UEngine]
UEP_TotalSize = 0x0

